package std;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import com.appian.connectedsystems.templateframework.sdk.configuration.TextPropertyDescriptor;

public interface ConstantKeys {

  // Values that need updating depending on the api you are connecting to:
  // CSP Auth
  String API_KEY = "apiKey";
  String ORGANIZATION = "organization";

  // API info
  String ROOT_URL = "https://api.openai.com/v1";
  String OPENAI = "openai";

  // Deprecated endpoints
  Set<String> PATHS_TO_REMOVE = new HashSet<>(Arrays.asList());
/*  "/audio/transcriptions", "/audio/translations"*/
/*  "/answers", "/classifications", "/engines", "/engines/{engine_id}",
      "/engines/{engine_id}/search"*/


  //Rest call types
  String GET = "GET";
  String POST = "POST";
  String PATCH = "PATCH";
  String DELETE = "DELETE";
  String JSONLINES = "JSONLINES";
  String CHOSEN_ENDPOINT = "chosenEndpoint";

  // folder/filename setting
  String FOLDER = "folder";
  String SAVED_FILENAME = "savedFileName";
  String OUTPUT_FILENAME = "outputFileName";
  String IS_FILE_EXPECTED = "isFileExpected";

  // Request body setting
  String REQ_BODY = "reqBody";
  String REQ_BODY_PROPERTIES = "reqBodyProperties";
  String NO_REQ_BODY = "noReqBody";
  TextPropertyDescriptor NO_REQ_BODY_UI = new TextPropertyDescriptor.TextPropertyDescriptorBuilder()
      .key(NO_REQ_BODY)
      .isReadOnly(true)
      .instructionText("No Request Body is required to execute this POST")
      .build();

  // Search bar
  String SEARCH = "search";

// Default Errors
  String AUTOGENERATED_ERROR_TITLE = "Autogenerated property with value 'text' must be removed before sending request";
  String AUTOGENERATED_ERROR_MESSAGE = "Please remove all autogenerated properties from request body before executing request.";
  String AUTOGENERATED_ERROR_DETAIL = "Autogenerated properties are marked 'text', 'true', '100', and '3.14' for string, boolean, integer, " +
      "and double properties, respectively. Make sure to update or remove these autogenerated properties before making " +
      "the request.";

  String FILE_SAVING_ERROR_TITLE = "Could not save file received from api.";
  String FOLDER_LOCATION_ERROR_MESSAGE = "Set desired folder location to save the incoming file.";
  String FILE_NAME_ERROR_MESSAGE = "Set desired file name save the incoming file.";

}
