package std;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.appian.connectedsystems.templateframework.sdk.configuration.RefreshPolicy;
import com.appian.connectedsystems.templateframework.sdk.configuration.TextPropertyDescriptor;

public interface ConstantKeys {

  // CSP Auth
  String API_KEY = "apiKey";
  String ORGANIZATION = "organization";


  String CHOSEN_ENDPOINT = "chosenEndpoint";
  String ROOT_URL = "https://api.openai.com/v1";

  // API Types
  String JOBS = "jobs";
  String CLAIMS = "claims";
  String POLICIES = "policies";
  String ACCOUNTS = "accounts";

  String OPENAI = "openai";

  //Rest call types
  String GET = "GET";

  String POST = "POST";
  String PATCH = "PATCH";
  String DELETE = "DELETE";

  String JSONLINES = "JSONLINES";
  String FOLDER = "folder";
  String SAVED_FILENAME = "savedFileName";
  String OUTPUT_FILENAME = "outputFileName";

  String IS_FILE_EXPECTED = "isFileExpected";

  Set<String> PATHS_TO_REMOVE = new HashSet<>(Arrays.asList("/answers", "/classifications", "/engines", "/engines/{engine_id}",
   "/engines/{engine_id}/search"));

  String NO_REQ_BODY = "noReqBody";

  TextPropertyDescriptor NO_REQ_BODY_UI = new TextPropertyDescriptor.TextPropertyDescriptorBuilder()
      .key(NO_REQ_BODY)
      .isReadOnly(true)
      .instructionText("No Request Body is required to execute this POST")
      .build();
  String INCLUDED_RESOURCES = "includedResources";

  String REQ_BODY = "reqBody";
  String REQ_BODY_PROPERTIES = "reqBodyProperties";

  String SEARCH = "search";


  String AUTOGENERATED_ERROR_TITLE = "Autogenerated property with value 'text' must be removed before sending request";
  String AUTOGENERATED_ERROR_MESSAGE = "Please remove all autogenerated properties from request body before executing request.";
  String AUTOGENERATED_ERROR_DETAIL = "Autogenerated properties are marked 'text', 'true', and '100' for string, boolean, and integer " +
      "properties, respectively. Make sure to update these autogenerated properties before making the request.";

}
